---
name: Links
description: Checks the links in a repo work

inputs:
  github-token:
    description: GitHub token
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default:
      --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Check links
      uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
        token: ${{ inputs.github-token }}
