name: Add Issue to project
on:
  workflow_call:

jobs:
  add_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}

      - name: Get project data
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/HRC-PhD/projects/1
          github-token: ${{ steps.app-token.outputs.token }}
